### ISSUE TITLE
india4movie error

### ISSUE THREAD

**Issue by kodifan2015** [irfancharania/icharania.repo#9]
Everytime i try to click on india4movie from the main page, it goes me this error "bad end tag: u"</scr' + 'ipt>", at line 450, column 143" movie rulz and full new movie work just fine. Can you please fix it or send me a work around? Any help will be appreciated. Thanks!

**Comment by irfancharania** [comment]
It's working fine on both my devices. Post [a log](http://xbmclogs.com/)

**Comment by kodifan2015** [comment]
It's working fine on my laptop too but this error keep showing up for my
jadoo 4 box, i tried reinstalling it, manually too since nothing worked. I
upgrade kodi to latest 15.2 but samething. Is there anyother way? Is there
a way to modify the data folder and i also i tried to find line 450 but
there isn't one in your script. Please help.

**Comment by irfancharania** [comment]
The issue sounds specific to your device.

One other thing to try is to delete the addon folder in
kodi/userdata/addon_data after uninstalling, and then reinstalling.

Aside from that, I have no idea.
On Nov 1, 2015 12:25 PM, "kodifan2015" <notifications@github.com> wrote:

It's working fine on my laptop too but this error keep showing up for my
jadoo 4 box, i tried reinstalling it, manually too since nothing worked. I
upgrade kodi to latest 15.2 but samething. Is there anyother way? Is there
a way to modify the data folder and i also i tried to find line 450 but
there isn't one in your script. Please help.
On Nov 1, 2015 2:11 PM, "Irfan Charania" <notifications@github.com> wrote:

> It's working fine on both my devices. Post a log <http://xbmclogs.com/>

>
> —
> Reply to this email directly or view it on GitHub
> <
https://github.com/irfancharania/icharania.repo/issues/9#issuecomment-152852590
>
> .

>

—
Reply to this email directly or view it on GitHub
<https://github.com/irfancharania/icharania.repo/issues/9#issuecomment-152860815>
.

**Comment by kodifan2015** [comment]
Thanks, i will try that.
